# -*- coding: utf-8 -*-
"""Atividade EBAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vv5CL3oJfVOcVotbkk5Uu-zo-Ro2n3e7
"""

nome = input('Olá, usúario, qual o seu nome?')
print(f'Olá {nome}, seja bem vindo a Calculadora')

continuar = 'sim' # Calculadora 'infinita'
while continuar == 'sim':
    num1 = float(input('Digite o primeiro número'))
    num2 = float(input('Digite o segundo número'))

    print('Operações disponíveis:')
    print('+ para soma')
    print('- para subtração')
    print('* para multiplicação')
    print('/ para divisão')

    resposta = input('Digite a operação que você deseja fazer')

    if resposta == '+':
        print(num1 + num2)
    elif resposta == '-':
        print(num1 - num2)
    elif resposta == '*':
        print(num1 * num2)
    elif resposta == '/':
        if num2 == 0:
            print('Erro: Divisão por zero não é permitida!')
        else:
            print(num1 / num2)
    else:
        print('Operação inválida')

    continuar = input('Deseja continuar? sim ou não').lower()